# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# 添加数据窗口ui文件
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(666, 244)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bd/icons8-user-60.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 641, 171))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.table_add_data = QtWidgets.QTableWidget(self.groupBox)
        self.table_add_data.setGeometry(QtCore.QRect(10, 20, 621, 141))
        self.table_add_data.setObjectName("table_add_data")
        self.table_add_data.setColumnCount(0)
        self.table_add_data.setRowCount(0)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 190, 581, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.reset_data_but = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("bd/icons8-time-lapse-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset_data_but.setIcon(icon1)
        self.reset_data_but.setObjectName("reset_data_but")
        self.horizontalLayout.addWidget(self.reset_data_but)
        self.confirm_data_but = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("bd/icons8-buy-for-cash-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.confirm_data_but.setIcon(icon2)
        self.confirm_data_but.setObjectName("confirm_data_but")
        self.horizontalLayout.addWidget(self.confirm_data_but)
        self.back_but = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("bd/icons8-back-arrow-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_but.setIcon(icon3)
        self.back_but.setObjectName("back_but")
        self.horizontalLayout.addWidget(self.back_but)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Data addition interface"))
        self.groupBox.setTitle(_translate("Form", "Add data"))
        self.reset_data_but.setText(_translate("Form", "Reset data"))
        self.confirm_data_but.setText(_translate("Form", "Confirm"))
        self.back_but.setText(_translate("Form", "Back"))
