# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feedback.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# 反馈界面ui文件

class Ui_feedback_form(object):
    def setupUi(self, feedback_form):
        feedback_form.setObjectName("feedback_form")
        feedback_form.resize(518, 258)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bd/icons8-buy-for-cash-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        feedback_form.setWindowIcon(icon)
        self.verticalLayoutWidget = QtWidgets.QWidget(feedback_form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(150, 20, 241, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.feedback_line = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.feedback_line.setPlainText("")
        self.feedback_line.setObjectName("feedback_line")
        self.verticalLayout.addWidget(self.feedback_line)
        self.formLayoutWidget = QtWidgets.QWidget(feedback_form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(150, 180, 241, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.name = QtWidgets.QLabel(self.formLayoutWidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.name.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name)
        self.name_line = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.name_line.setObjectName("name_line")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_line)
        self.back_but_login = QtWidgets.QPushButton(self.formLayoutWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("bd/icons8-back-arrow-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back_but_login.setIcon(icon1)
        self.back_but_login.setObjectName("back_but_login")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.back_but_login)
        self.submit_but = QtWidgets.QPushButton(self.formLayoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("bd/icons8-up-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submit_but.setIcon(icon2)
        self.submit_but.setObjectName("submit_but")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.submit_but)
        self.label = QtWidgets.QLabel(feedback_form)
        self.label.setGeometry(QtCore.QRect(0, 0, 521, 261))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("bd/bd.jpg"))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(feedback_form)
        self.line.setGeometry(QtCore.QRect(20, 240, 471, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.line.setFont(font)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label.raise_()
        self.verticalLayoutWidget.raise_()
        self.formLayoutWidget.raise_()
        self.line.raise_()

        self.retranslateUi(feedback_form)
        QtCore.QMetaObject.connectSlotsByName(feedback_form)

    def retranslateUi(self, feedback_form):
        _translate = QtCore.QCoreApplication.translate
        feedback_form.setWindowTitle(_translate("feedback_form", "User feedback"))
        self.feedback_line.setPlaceholderText(_translate("feedback_form", "Fill in the feedback information"))
        self.name.setText(_translate("feedback_form", "Username"))
        self.back_but_login.setText(_translate("feedback_form", "Back"))
        self.submit_but.setText(_translate("feedback_form", "Submit"))
