# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# 系统信息窗口ui文件 【非必要情况下，不可修改】

class Ui_sys_Form(object):
    def setupUi(self, sys_Form):
        sys_Form.setObjectName("sys_Form")
        sys_Form.resize(400, 261)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("bd/icons8-system-48.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sys_Form.setWindowIcon(icon)
        self.infor_board = QtWidgets.QLabel(sys_Form)
        self.infor_board.setEnabled(True)
        self.infor_board.setGeometry(QtCore.QRect(10, 10, 381, 241))
        self.infor_board.setText("")
        self.infor_board.setPixmap(QtGui.QPixmap("bd/bluebd.jpg"))
        self.infor_board.setObjectName("infor_board")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(sys_Form)
        self.plainTextEdit.setEnabled(False)
        self.plainTextEdit.setGeometry(QtCore.QRect(20, 20, 361, 201))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(sys_Form)
        QtCore.QMetaObject.connectSlotsByName(sys_Form)

    def retranslateUi(self, sys_Form):
        _translate = QtCore.QCoreApplication.translate
        sys_Form.setWindowTitle(_translate("sys_Form", "System information"))
